# Generated by Django 3.1.3 on 2020-11-21 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_link', '0003_teamrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.IntegerField()),
                ('ques_image', models.ImageField(upload_to='ques_image')),
                ('answer', models.TextField()),
            ],
            options={
                'ordering': ['ques_no'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='cur_ques_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='teamrelation',
            unique_together={('user', 'team')},
        ),
    ]
