# Generated by Django 3.1.3 on 2020-11-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_link', '0004_auto_20201121_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cur_ques_no',
            field=models.IntegerField(default=1),
        ),
    ]
