# Generated by Django 3.1.3 on 2020-11-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_link', '0007_auto_20201121_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
