# Generated by Django 3.1.3 on 2020-11-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_link', '0009_answerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_ques_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_ques_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='code_link.team')),
            ],
        ),
    ]
