# Generated by Django 3.1.3 on 2020-11-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_link', '0010_auto_20201121_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranks',
            options={'ordering': ['cur_ques_no', 'created_at']},
        ),
    ]
