# Generated by Django 3.1.3 on 2020-11-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_link', '0011_auto_20201121_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ques_image',
        ),
        migrations.AddField(
            model_name='question',
            name='ques_url',
            field=models.TextField(default=''),
        ),
    ]
